# Generated by Django 4.0.5 on 2022-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(help_text='Enter url books image', null=True),
        ),
    ]
