# Generated by Django 4.0.5 on 2022-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='number',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
