# Generated by Django 4.0.5 on 2022-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_purchase_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
