# Generated by Django 4.0.5 on 2022-07-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_rename_number_purchase_phone_number_purchase_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
